### ISSUE TITLE
takePicture failed

### ISSUE THREAD

**Issue by americosfacebook** [nesterov-n/Smiley#1]
Exception thrown from receiver.
                                                                 java.lang.RuntimeException: takePicture failed
                                                                     at android.hardware.Camera.native_takePicture(Native Method)
                                                                     at android.hardware.Camera.takePicture(Camera.java:1475)
                                                                     at com.google.android.gms.vision.CameraSource.takePicture(Unknown Source)
                                                                     at ru.nnesterov.smiley.FaceTrackerActivity.takeShot(FaceTrackerActivity.java:267)
                                                                     at ru.nnesterov.smiley.FaceTrackerActivity.access$300(FaceTrackerActivity.java:52)
                                                                     at ru.nnesterov.smiley.FaceTrackerActivity$GraphicFaceTracker.onUpdate(FaceTrackerActivity.java:332)
                                                                     at ru.nnesterov.smiley.FaceTrackerActivity$GraphicFaceTracker.onUpdate(FaceTrackerActivity.java:305)
                                                                     at com.google.android.gms.vision.MultiProcessor.zzc(Unknown Source)
                                                                     at com.google.android.gms.vision.MultiProcessor.receiveDetections(Unknown Source)
                                                                     at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
                                                                     at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by nesterov-n** [comment]
Thanks for you issue. Can you provide device model and android OS version where this exception is thrown?

**Comment by americosfacebook** [comment]
Manufacturer : Sony 
Scan Version : 1.0 
Model : C6602 
OS Version : 5.1.1 
Build ID : 10.7.A.0.222 
thanks for replying.

**Comment by nesterov-n** [comment]
@americosfacebook Thanks I will try to reproduce this issue

**Comment by americosfacebook** [comment]
thanks in advance.

**Comment by adv-zl** [comment]
Any result?
